using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Shapes;
using Microsoft.Phone.Controls;
using Microsoft.Phone.Tasks;
using SanzaiGuokr.Model;
using SanzaiGuokr.ViewModel;
using Microsoft.Phone.Shell;

namespace SanzaiGuokr
{
    public partial class ViewComments : PhoneApplicationPage
    {
        public ViewComments()
        {
            InitializeComponent();

            NavigationInTransition nvs = new NavigationInTransition();
            NavigationTransition n = new NavigationTransition();

#if DEBUG
            debugTextBox.Visibility = System.Windows.Visibility.Visible;
            debugButton.Visibility = System.Windows.Visibility.Visible;
#endif
        }

        private void email_share_Click(object sender, EventArgs e)
        {
            EmailComposeTask t = new EmailComposeTask();
            var a = (this.DataContext as ReadArticleViewModel).the_article;
            t.Subject = "[果壳] "+a.title;
            t.Body = string.Format("标准链接： {0}\n移动版链接： {1}\n\n{2} - {3}\n\n{4}\n\n{5}",
                "http://www.guokr.com/article/" + a.id.ToString() + "/",
                a.url,
                a.title.TrimEnd(new char[] { ' ', '\n', '\t', '\r' }), a.minisite_name,
                a.Abstract,
                "Generated by 山寨果壳");
            t.Show();
        }

        private void PhoneApplicationPage_Loaded(object sender, RoutedEventArgs e)
        {
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            MessageBox.Show("debug");
        }
    }
}