using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Shapes;
using Microsoft.Phone.Controls;
using Microsoft.Phone.Tasks;
using SanzaiGuokr.Model;
using SanzaiGuokr.ViewModel;
using Microsoft.Phone.Shell;
using System.Threading.Tasks;
using GalaSoft.MvvmLight.Messaging;
using SanzaiGuokr.Messages;
using SanzaiGuokr.GuokrObject;
using SanzaiGuokr.Util;
using SanzaiGuokrCore.Util;
using webbrowsertest;

namespace SanzaiGuokr
{
    public partial class ReadPost : PhoneApplicationPage
    {
        public ReadPost()
        {
            InitializeComponent();

            NavigationInTransition nvs = new NavigationInTransition();
            NavigationTransition n = new NavigationTransition();

#if PIPROFILING
            var pi = new ProgressIndicator();
            pi.IsVisible = true;
            SystemTray.SetProgressIndicator(this, pi);
            Messenger.Default.Register<SetProgressIndicator>(this, (a) => Common.ProcessProgressIndicator(SystemTray.GetProgressIndicator(this), a));
#endif
        }

        private GuokrPost a
        {
            get
            {
                var dc = (this.DataContext as ReadPostViewModel);
                if (dc == null) return null;

                return dc.the_article;
            }
        }

        private async void email_share_Click(object sender, EventArgs e)
        {
#if false
            EmailComposeTask t = new EmailComposeTask();

            if (a == null) return;
            var html = a.HtmlContent;
            var s = await Task.Run(() =>
                {
                    return Util.Common.FlattenHtmlConentToText(html);
                });
            t.Subject = "[果壳] " + a.title;
            t.Body = string.Format("标准链接： {0}\n移动版链接： {1}\n\n{2} - {3}\n\n{4}\n\n{5}",
                "http://www.guokr.com/article/" + a.id.ToString() + "/",
                a.url,
                a.title.TrimEnd(new char[] { ' ', '\n', '\t', '\r' }), a.minisite_name,
                s,
                "Generated by 山寨果壳");
            t.Show();
#endif
        }

        private void weibo_share_Click(object sender, EventArgs e)
        {
#if false
            if (ViewModelLocator.ApplicationSettingsStatic.WeiboAccountLoginStatus)
            {
                // post new weibo
                if (a == null) return;
                Messenger.Default.Send<CreateAWeibo>(new CreateAWeibo() { Article = a, Type = CreateAWeibo.ShareWeiboType.ShareGuokrArticle });
                NavigationService.Navigate(new Uri("/WeiboCreate.xaml", UriKind.Relative));
            }
            else
            {
                // setup account
                NavigationService.Navigate(new Uri("/WeiboLoginPage2.xaml", UriKind.Relative));
            }
#endif
        }

        private void PhoneApplicationPage_Loaded(object sender, RoutedEventArgs e)
        {
            a.refresh_comment_count();
            SystemTray.IsVisible = true;
        }

        private void wbScriptNotify(object sender, Microsoft.Phone.Controls.NotifyEventArgs e)
        {
            var split = e.Value.IndexOf('|');
            if (split == -1)
                throw new ArgumentException("There is a code bug in ScriptNotify");

            var type = e.Value.Substring(0, split);
            var data = e.Value.Substring(split + 1);
            if (type == "img")
                Messenger.Default.Send<ViewImageMessage>(new ViewImageMessage()
                {
                    small_uri = data,
                    med_uri = (new GuokrImageInfo(data)).ToImage(),
                    large_uri = data
                });
            else if (type == "a")
            {
                if (data.IndexOf("about:") == 0)
                    data = data.Replace("about:", "http://www.guokr.com");
                try
                {
                    if (data.Contains("swf"))
                        GoogleAnalytics.EasyTracker.GetTracker().SendEvent("OpenSWF", data, "ReadPost", 1);
                    var t = new WebBrowserTask();
                    t.Uri = new Uri(data, UriKind.Absolute);
                    t.Show();
                }
                catch (Exception ee)
                {
                    DebugLogging.Append("ScriptNotfiy", e.Value, ee.Message);
                }
            }
        }

        protected override void OnBackKeyPress(System.ComponentModel.CancelEventArgs e)
        {
            if (ViewModelLocator.MainStatic.ImagePopupOpened)
            {
                ViewModelLocator.MainStatic.ImagePopupOpened = false;
                e.Cancel = true;
            }
            else
            {
                Messenger.Default.Unregister(this);
                MYFUCKYOUWP.ClearValue(MyWebBrowser.SourceHtmlProperty);
            }
            base.OnBackKeyPress(e);
        }

        private void GestureListener_Flick(object sender, FlickGestureEventArgs e)
        {
            if (ViewModelLocator.MainStatic.ImagePopupOpened)
                return;

            if (e.Direction == System.Windows.Controls.Orientation.Horizontal
                && e.Angle > 160 && e.Angle < 200)
                (this.DataContext as ReadPostViewModel).the_article.ReadThisArticleComment.Execute(null);
#if false
            else if (e.Direction == System.Windows.Controls.Orientation.Horizontal
                && (e.Angle > 350 || e.Angle < 40)
                && NavigationService.CanGoBack)
                NavigationService.GoBack();
#endif
        }

    }
}